=== andreiticu/ProiectXML/log.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT root (date1)>
<!ATTLIST root
  xmlns CDATA #FIXED ''>

<!ELEMENT date1 (user,pass)>
<!ATTLIST date1
  xmlns CDATA #FIXED ''>

<!ELEMENT user (#PCDATA)>
<!ATTLIST user
  xmlns CDATA #FIXED ''>

<!ELEMENT pass (#PCDATA)>
<!ATTLIST pass
  xmlns CDATA #FIXED ''>

=== andreiticu/ProiectXML/log.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "log.dtd">
<root>
    <date1>
        <user>doru'sfood@yahoo.com</user>
        <pass>654321</pass>    
    </date1> 
    <date1>
        <user>doru'sfood@yahoo.com</user>
        <pass>654321</pass>    
    </date1> 
    <date1>
        <user>doru'sfood@yahoo.com</user>
        <pass>654321</pass>    
    </date1> 
</root>
